### PR TITLE
token alive function written

### PR DESCRIPTION
**Pull request by veryshyjelly**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by proffapt — COMMENTED** [review]
Why itni mehnat?

**Comment by veryshyjelly** [comment]
> Why itni mehnat?

konsi mehnat?

**Comment by proffapt** [comment]
> > Why itni mehnat?
> 
> konsi mehnat? description to automatic aaya tha

I meant what's the benefit of finding the path inside the cookie..

image
upar wale are constant fields, inside `{}` are the ones which separates out the headers, and content-type seems to me the best method to distinguish.

**Comment by veryshyjelly** [comment]
okay

**Comment by proffapt** [comment]
There are actually 3 cases for some reason..

image

And this is the only thing which exist in all of them and distinguishes the 1 from the other two

One case which you might have not checked is jab pehli baar login hota try printing the headers.. for some reason it is a bit different from the login when you directly use the token.

**Comment by proffapt** [comment]
> Sir my code will work

so will this one :looksaway:

**Pull request closed without merging**
